export const ACTIONS = {
  GET_PROFILE   : "GET_PROFILE",
  LOGIN         :"LOGIN",
  GET_CHATLIST  : "GET_CHATLIST",
  GET_CONTACT   : "GET_CONTACT",
  GET_USERS     : "GET_USERS",
  GET_ABOUTUS   : "GET_ABOUTUS",
}